# Generated by Django 5.2.12 on 2026-03-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0003_narrativememory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committedscene",
            name="text",
        ),
        migrations.AddField(
            model_name="committedscene",
            name="cassandra_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="committedscene",
            name="combined_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="committedscene",
            name="user_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
