# Generated by Django 5.2.12 on 2026-03-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0004_remove_committedscene_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="prior_scene_state_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="proposal",
            name="proposed_scene_state_json",
            field=models.JSONField(default=dict),
        ),
    ]
