# Generated by Django 5.2.12 on 2026-03-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0005_proposal_prior_scene_state_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="scene_state_update_json",
        ),
        migrations.AddField(
            model_name="proposal",
            name="proposed_narrative_memories_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="proposal",
            name="revision_change_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="proposal",
            name="revision_intent_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
