# Generated by Django 5.2.12 on 2026-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0006_remove_proposal_scene_state_update_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="scene_state_update_json",
            field=models.JSONField(default=dict),
        ),
    ]
