# Generated by Django 5.2.12 on 2026-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0007_proposal_scene_state_update_json"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="proposed_narrative_memories_json",
            new_name="editors_craft_memory_json",
        ),
        migrations.AlterField(
            model_name="proposal",
            name="pending_intents_json",
            field=models.JSONField(default=list),
        ),
    ]
