# Generated by Django 5.2.12 on 2026-03-27 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "story",
            "0008_rename_proposed_narrative_memories_json_proposal_editors_craft_memory_json_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterBelief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "subject_slug",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("belief", models.TextField()),
                ("confidence", models.FloatField(default=0.5)),
                ("is_true", models.BooleanField(blank=True, null=True)),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "memory_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterPerception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("impression_json", models.JSONField(blank=True, default=dict)),
                ("relationship_json", models.JSONField(blank=True, default=dict)),
                ("belief_json", models.JSONField(blank=True, default=dict)),
                ("arc_json", models.JSONField(blank=True, default=dict)),
                ("trust", models.FloatField(default=0.0)),
                ("attraction", models.FloatField(default=0.0)),
                ("fear", models.FloatField(default=0.0)),
                ("resentment", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("archetype", models.CharField(blank=True, default="", max_length=100)),
                ("personality_json", models.JSONField(blank=True, default=dict)),
                ("diction_json", models.JSONField(blank=True, default=dict)),
                ("craft_notes_json", models.JSONField(blank=True, default=dict)),
                ("background_json", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotional_state_json", models.JSONField(blank=True, default=dict)),
                ("goals_json", models.JSONField(blank=True, default=dict)),
                ("internal_conflicts_json", models.JSONField(blank=True, default=dict)),
                ("status_json", models.JSONField(blank=True, default=dict)),
                ("active_intents_json", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="diction_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="character",
            name="is_player",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="character",
            name="profile_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="status_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="pending_intents_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["world", "slug"], name="story_chara_world_i_4de26e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["world", "is_active"], name="story_chara_world_i_68c1d4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.UniqueConstraint(
                fields=("world", "slug"), name="uniq_character_slug_per_world"
            ),
        ),
        migrations.AddField(
            model_name="characterbelief",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beliefs",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="characterbelief",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_beliefs",
                to="story.world",
            ),
        ),
        migrations.AddField(
            model_name="charactermemory",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="charactermemory",
            name="related_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memories_about_me",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="charactermemory",
            name="source_scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_memories",
                to="story.committedscene",
            ),
        ),
        migrations.AddField(
            model_name="charactermemory",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_memories",
                to="story.world",
            ),
        ),
        migrations.AddField(
            model_name="characterperception",
            name="observer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_perceptions",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="characterperception",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_perceptions",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="characterperception",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_perceptions",
                to="story.world",
            ),
        ),
        migrations.AddField(
            model_name="characterprofile",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="characterstate",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state",
                to="story.character",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterperception",
            constraint=models.UniqueConstraint(
                fields=("world", "observer", "target"), name="uniq_character_perception"
            ),
        ),
    ]
