# Generated by Django 5.2.12 on 2026-04-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0009_characterbelief_charactermemory_characterperception_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="pending_intents_json",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="prior_scene_state_json",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="proposed_scene_state_json",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="scene_state_update_json",
        ),
        migrations.AddField(
            model_name="proposal",
            name="character_authored_intents_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
