# Generated by Django 5.2.12 on 2026-04-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0010_remove_proposal_pending_intents_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterPerceptionChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_source",
                    models.CharField(blank=True, default="scene_delta", max_length=50),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("impression_json", models.JSONField(blank=True, default=dict)),
                ("relationship_json", models.JSONField(blank=True, default=dict)),
                ("belief_json", models.JSONField(blank=True, default=dict)),
                ("arc_json", models.JSONField(blank=True, default=dict)),
                ("trust_delta", models.FloatField(default=0.0)),
                ("attraction_delta", models.FloatField(default=0.0)),
                ("fear_delta", models.FloatField(default=0.0)),
                ("resentment_delta", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterStateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_source",
                    models.CharField(blank=True, default="scene_delta", max_length=50),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("emotional_state_json", models.JSONField(blank=True, default=dict)),
                ("goals_json", models.JSONField(blank=True, default=dict)),
                ("internal_conflicts_json", models.JSONField(blank=True, default=dict)),
                ("motivational_state_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="characterstate",
            old_name="active_intents_json",
            new_name="motivational_state_json",
        ),
        migrations.RemoveField(
            model_name="character",
            name="diction_json",
        ),
        migrations.RemoveField(
            model_name="character",
            name="profile_json",
        ),
        migrations.RemoveField(
            model_name="character",
            name="status_json",
        ),
        migrations.RemoveField(
            model_name="characterstate",
            name="status_json",
        ),
        migrations.RemoveField(
            model_name="committedscene",
            name="combined_text",
        ),
        migrations.AddField(
            model_name="characterbelief",
            name="source_scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_beliefs",
                to="story.committedscene",
            ),
        ),
        migrations.AddField(
            model_name="committedscene",
            name="turn_number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="narrativememory",
            name="source_scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="narrative_memories",
                to="story.committedscene",
            ),
        ),
        migrations.AlterField(
            model_name="charactermemory",
            name="source_scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_memories",
                to="story.committedscene",
            ),
        ),
        migrations.AddIndex(
            model_name="committedscene",
            index=models.Index(
                fields=["world", "turn_number"], name="story_commi_world_i_83191a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="committedscene",
            index=models.Index(
                fields=["world", "created_at"], name="story_commi_world_i_aaf415_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="committedscene",
            constraint=models.UniqueConstraint(
                fields=("world", "turn_number"),
                name="uniq_committed_scene_turn_number_per_world",
            ),
        ),
        migrations.AddField(
            model_name="characterperceptionchange",
            name="observer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perception_changes_made",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="characterperceptionchange",
            name="source_scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_perception_changes",
                to="story.committedscene",
            ),
        ),
        migrations.AddField(
            model_name="characterperceptionchange",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perception_changes_received",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="characterperceptionchange",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_perception_changes",
                to="story.world",
            ),
        ),
        migrations.AddField(
            model_name="characterstatechange",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_changes",
                to="story.character",
            ),
        ),
        migrations.AddField(
            model_name="characterstatechange",
            name="source_scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_state_changes",
                to="story.committedscene",
            ),
        ),
        migrations.AddField(
            model_name="characterstatechange",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_state_changes",
                to="story.world",
            ),
        ),
        migrations.AddIndex(
            model_name="characterperceptionchange",
            index=models.Index(
                fields=["world", "observer", "target"],
                name="story_chara_world_i_700ed5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="characterperceptionchange",
            index=models.Index(
                fields=["world", "source_scene"], name="story_chara_world_i_fffab7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="characterperceptionchange",
            index=models.Index(
                fields=["observer", "target", "created_at"],
                name="story_chara_observe_cce95d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="characterstatechange",
            index=models.Index(
                fields=["world", "character"], name="story_chara_world_i_99e63d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="characterstatechange",
            index=models.Index(
                fields=["world", "source_scene"], name="story_chara_world_i_368c02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="characterstatechange",
            index=models.Index(
                fields=["character", "created_at"],
                name="story_chara_charact_94eb7f_idx",
            ),
        ),
    ]
