# Generated by Django 5.2.12 on 2026-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0011_characterperceptionchange_characterstatechange_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="character_contributions_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="scenestate",
            name="alias_cache_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
