# Generated by Django 5.2.12 on 2026-04-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0012_proposal_character_contributions_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="agent_provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("grok", "Grok")],
                default="openai",
                max_length=32,
            ),
        ),
    ]
