# Generated by Django 5.2.12 on 2026-04-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0013_character_agent_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="scene_events_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
