# Generated by Django 5.2.12 on 2026-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0014_proposal_scene_events_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterprofile",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="characterprofile",
            name="pronouns_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
