# Generated by Django 5.2.12 on 2026-05-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0015_characterprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="alias_cache_update_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="proposal",
            name="proposed_scene_state_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="proposal",
            name="resolved_character_experience_updates_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="proposal",
            name="resolved_pending_intents_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="proposal",
            name="scene_state_update_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
