# Generated by Django 5.2.12 on 2026-05-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0016_proposal_alias_cache_update_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="committedscene",
            name="scene_events_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
