# Generated by Django 5.2.12 on 2026-05-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0017_committedscene_scene_events_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterbelief",
            name="belief_status",
            field=models.CharField(
                choices=[
                    ("transient", "Transient"),
                    ("reinforced", "Reinforced"),
                    ("promoted", "Promoted"),
                    ("discarded", "Discarded"),
                ],
                default="transient",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="characterprofile",
            name="permabeliefs_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
