# Generated by Django 5.2.12 on 2026-06-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0018_characterbelief_belief_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="character_agent_debug_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
