# Generated by Django 5.2.12 on 2026-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0019_proposal_character_agent_debug_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenestate",
            name="topology_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
