# Generated by Django 5.2.12 on 2026-06-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0020_scenestate_topology_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_number", models.PositiveIntegerField()),
                ("perceived_text", models.TextField(blank=True)),
                ("perception_json", models.JSONField(blank=True, default=dict)),
                ("participation", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_scenes",
                        to="story.character",
                    ),
                ),
                (
                    "source_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_scenes",
                        to="story.committedscene",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_scenes",
                        to="story.world",
                    ),
                ),
            ],
            options={
                "ordering": ["turn_number", "id"],
                "unique_together": {("character", "source_scene")},
            },
        ),
    ]
