# Generated by Django 5.2.12 on 2026-06-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0021_characterscene"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterscene",
            name="event_record_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="event_record_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="subjective_scene_text",
            field=models.TextField(blank=True),
        ),
    ]
