# Generated by Django 5.2.12 on 2026-06-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0022_characterscene_event_record_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterscene",
            name="aftermath_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="aftermath_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
