# Generated by Django 5.2.12 on 2026-06-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0023_characterscene_aftermath_processed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="committedscene",
            name="cassandra_aftermath_processed",
            field=models.BooleanField(default=False),
        ),
    ]
