# Generated by Django 5.2.12 on 2026-06-11 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0024_committedscene_cassandra_aftermath_processed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterscene",
            options={"ordering": ["turn_number", "character__slug"]},
        ),
        migrations.AlterUniqueTogether(
            name="characterscene",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="acting_character_snapshot_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="active_pressure",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="anticipated_consequence",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="attempted_action",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="attempted_dialogue",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="authored_intent_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="beliefs_created_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="beliefs_in_play_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="body_motion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="current_turn_reflection_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="emotional_posture",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="internal_intent",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="interrupt_priority",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="local_scene_state_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="memories_created_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="memory_pressures_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="observed_focus_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="perception_updates_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="previous_scene_aftermath_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="proposed_effects_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="required_audibility",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="required_visibility",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="scene_contribution_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="state_after_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="state_before_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="state_update_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="target_slugs_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="characterscene",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="characterscene",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="story.character"
            ),
        ),
        migrations.AlterField(
            model_name="characterscene",
            name="event_record_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="characterscene",
            name="participation",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="characterscene",
            name="source_scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_scenes",
                to="story.committedscene",
            ),
        ),
        migrations.AlterField(
            model_name="characterscene",
            name="subjective_scene_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="characterscene",
            name="turn_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="characterscene",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="story.world"
            ),
        ),
        migrations.AddIndex(
            model_name="characterscene",
            index=models.Index(
                fields=["world", "character", "turn_number"],
                name="story_chara_world_i_2e15fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="characterscene",
            index=models.Index(
                fields=["source_scene", "character"],
                name="story_chara_source__c5faa0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="characterscene",
            index=models.Index(
                fields=["aftermath_processed"], name="story_chara_afterma_7dc2f7_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="characterscene",
            name="aftermath_processed_at",
        ),
        migrations.RemoveField(
            model_name="characterscene",
            name="perceived_text",
        ),
        migrations.RemoveField(
            model_name="characterscene",
            name="perception_json",
        ),
    ]
