# Generated by Django 5.2.12 on 2026-07-05 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0029_multi_subject_beliefs_and_memories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterperception",
            name="arc_json",
        ),
        migrations.RemoveField(
            model_name="characterperceptionchange",
            name="arc_json",
        ),
    ]
