# Generated by Django 5.2.12 on 2026-07-05 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0030_remove_characterperception_arc_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryArc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dormant", "Dormant"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("world", "World"),
                            ("character", "Character"),
                            ("relationship", "Relationship"),
                            ("group", "Group"),
                        ],
                        default="world",
                        max_length=40,
                    ),
                ),
                ("subject_slugs_json", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, default="")),
                ("narrator_guidance", models.TextField(blank=True, default="")),
                ("character_lenses_json", models.JSONField(blank=True, default=dict)),
                ("priority", models.FloatField(default=0.5)),
                (
                    "current_phase",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("horizon", models.CharField(blank=True, default="", max_length=160)),
                ("constraints", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_arcs",
                        to="story.world",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-updated_at", "title"],
                "indexes": [
                    models.Index(
                        fields=["world", "status", "priority"],
                        name="story_story_world_i_6ec0d2_idx",
                    ),
                    models.Index(
                        fields=["world", "scope"], name="story_story_world_i_6faba9_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("world", "slug"), name="uniq_story_arc_slug_per_world"
                    )
                ],
            },
        ),
    ]
