# Generated by Django 5.2.12 on 2026-07-12 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0031_storyarc"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectiveRelationshipEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_label",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("knowledge_basis", models.TextField(blank=True, default="")),
                ("confidence", models.FloatField(default=0.5)),
                ("open_questions_json", models.JSONField(blank=True, default=list)),
                ("directional_notes_json", models.JSONField(blank=True, default=dict)),
                ("last_change_summary", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "observer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edges_observed",
                        to="story.character",
                    ),
                ),
                (
                    "subject_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edges_as_a",
                        to="story.character",
                    ),
                ),
                (
                    "subject_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edges_as_b",
                        to="story.character",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edges",
                        to="story.world",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectiveRelationshipEdgeChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_source",
                    models.CharField(blank=True, default="scene_delta", max_length=50),
                ),
                (
                    "relationship_label",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("revised_summary", models.TextField(blank=True, default="")),
                ("knowledge_basis", models.TextField(blank=True, default="")),
                ("confidence", models.FloatField(default=0.5)),
                ("open_questions_json", models.JSONField(blank=True, default=list)),
                ("directional_notes_json", models.JSONField(blank=True, default=dict)),
                ("access_gate_json", models.JSONField(blank=True, default=dict)),
                (
                    "change_layer",
                    models.CharField(
                        choices=[
                            ("raw", "Raw"),
                            ("past", "Past"),
                            ("history", "History"),
                        ],
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("is_context_active", models.BooleanField(default=True)),
                ("source_change_ids_json", models.JSONField(blank=True, default=list)),
                ("source_change_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compacted_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compacted_source_edge_changes",
                        to="story.subjectiverelationshipedgechange",
                    ),
                ),
                (
                    "current_edge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changes",
                        to="story.subjectiverelationshipedge",
                    ),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edge_changes_observed",
                        to="story.character",
                    ),
                ),
                (
                    "source_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edge_changes",
                        to="story.committedscene",
                    ),
                ),
                (
                    "subject_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edge_changes_as_a",
                        to="story.character",
                    ),
                ),
                (
                    "subject_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edge_changes_as_b",
                        to="story.character",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjective_relationship_edge_changes",
                        to="story.world",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subjectiverelationshipedge",
            index=models.Index(
                fields=["world", "observer"], name="story_edge_observer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectiverelationshipedge",
            index=models.Index(
                fields=["world", "subject_a", "subject_b"], name="story_edge_pair_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectiverelationshipedge",
            constraint=models.UniqueConstraint(
                fields=("world", "observer", "subject_a", "subject_b"),
                name="uniq_subjective_edge",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectiverelationshipedgechange",
            index=models.Index(
                fields=["world", "observer", "subject_a", "subject_b"],
                name="story_edge_ch_pair_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectiverelationshipedgechange",
            index=models.Index(
                fields=["world", "source_scene"], name="story_edge_ch_scene_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectiverelationshipedgechange",
            index=models.Index(
                fields=[
                    "world",
                    "observer",
                    "subject_a",
                    "subject_b",
                    "change_layer",
                    "is_context_active",
                ],
                name="story_edge_ch_ctx_idx",
            ),
        ),
    ]
