# Generated by Django 5.2.12 on 2026-07-13 00:32

import django.db.models.deletion
import story.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0032_subjectiverelationshipedge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterVisualIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("appearance_summary", models.TextField(blank=True, default="")),
                ("canonical_identity_prompt", models.TextField(blank=True, default="")),
                ("negative_identity_prompt", models.TextField(blank=True, default="")),
                ("traits_json", models.JSONField(blank=True, default=dict)),
                ("allowed_variations_json", models.JSONField(blank=True, default=dict)),
                (
                    "recognition_aliases_json",
                    models.JSONField(blank=True, default=list),
                ),
                ("provider_notes_json", models.JSONField(blank=True, default=dict)),
                ("current_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_identity",
                        to="story.character",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_visual_identities",
                        to="story.world",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterVisualIdentityVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("appearance_summary", models.TextField(blank=True, default="")),
                ("canonical_identity_prompt", models.TextField(blank=True, default="")),
                ("negative_identity_prompt", models.TextField(blank=True, default="")),
                ("traits_json", models.JSONField(blank=True, default=dict)),
                ("allowed_variations_json", models.JSONField(blank=True, default=dict)),
                (
                    "recognition_aliases_json",
                    models.JSONField(blank=True, default=list),
                ),
                ("provider_notes_json", models.JSONField(blank=True, default=dict)),
                ("change_reason", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("imported", "Imported"),
                            ("generated", "Generated"),
                            ("revised", "Revised"),
                        ],
                        default="manual",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_identity_versions",
                        to="story.character",
                    ),
                ),
                (
                    "visual_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="story.charactervisualidentity",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_visual_identity_versions",
                        to="story.world",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="CharacterVisualReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=story.models.character_visual_reference_upload_path
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("face", "Face"),
                            ("full_body", "Full body"),
                            ("expression_sheet", "Expression sheet"),
                            ("outfit", "Outfit"),
                            ("mood_reference", "Mood reference"),
                            ("generated_reference", "Generated reference"),
                            ("other", "Other"),
                        ],
                        default="face",
                        max_length=40,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("caption", models.TextField(blank=True, default="")),
                ("generation_prompt", models.TextField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=80)),
                (
                    "provider_asset_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_references",
                        to="story.character",
                    ),
                ),
                (
                    "identity_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="references",
                        to="story.charactervisualidentityversion",
                    ),
                ),
                (
                    "visual_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="story.charactervisualidentity",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_visual_references",
                        to="story.world",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="charactervisualidentity",
            index=models.Index(
                fields=["world", "status"], name="story_chara_world_i_b317d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="charactervisualidentity",
            index=models.Index(
                fields=["world", "character"], name="story_chara_world_i_51f124_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="charactervisualidentityversion",
            index=models.Index(
                fields=["world", "character", "version_number"],
                name="story_chara_world_i_071406_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactervisualidentityversion",
            constraint=models.UniqueConstraint(
                fields=("visual_identity", "version_number"),
                name="uniq_visual_identity_version_number",
            ),
        ),
        migrations.AddIndex(
            model_name="charactervisualreference",
            index=models.Index(
                fields=["world", "character", "kind"],
                name="story_chara_world_i_379a38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="charactervisualreference",
            index=models.Index(
                fields=["visual_identity", "is_primary"],
                name="story_chara_visual__c6ca19_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactervisualreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("character",),
                name="uniq_primary_visual_reference_per_character",
            ),
        ),
    ]
