# Generated by Django 5.2.12 on 2026-07-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0033_charactervisualidentity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="charactervisualreference",
            name="uniq_primary_visual_reference_per_character",
        ),
        migrations.AddConstraint(
            model_name="charactervisualreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("character", "identity_version"),
                name="uniq_primary_visual_reference_per_character_version",
            ),
        ),
    ]
