# Generated by Django 5.2.12 on 2026-07-13 21:04

from django.db import migrations, models


def normalize_active_visual_identity_versions(apps, schema_editor):
    CharacterVisualIdentity = apps.get_model("story", "CharacterVisualIdentity")
    CharacterVisualIdentityVersion = apps.get_model(
        "story",
        "CharacterVisualIdentityVersion",
    )

    for identity in CharacterVisualIdentity.objects.all():
        active_versions = list(
            CharacterVisualIdentityVersion.objects
            .filter(visual_identity=identity, status="active")
            .order_by("version_number")
        )

        if len(active_versions) <= 1:
            continue

        keep = None
        if identity.current_version:
            keep = next(
                (
                    version for version in active_versions
                    if version.version_number == identity.current_version
                ),
                None,
            )

        if keep is None:
            keep = active_versions[-1]

        CharacterVisualIdentityVersion.objects.filter(
            id__in=[
                version.id
                for version in active_versions
                if version.id != keep.id
            ]
        ).update(status="retired")

        if identity.current_version != keep.version_number:
            identity.current_version = keep.version_number
        identity.status = keep.status
        identity.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "story",
            "0034_remove_charactervisualreference_uniq_primary_visual_reference_per_character_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            normalize_active_visual_identity_versions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="charactervisualidentityversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("visual_identity",),
                name="uniq_active_visual_identity_version",
            ),
        ),
    ]
