# Generated by Django 5.2.12 on 2026-07-14 00:26

import django.db.models.deletion
import story.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "story",
            "0035_charactervisualidentityversion_uniq_active_visual_identity_version",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedMediaJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("wanda_identity", "Wanda identity"),
                            ("approved_scene", "Approved scene"),
                        ],
                        default="wanda_identity",
                        max_length=40,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        max_length=20,
                    ),
                ),
                (
                    "generation_mode",
                    models.CharField(
                        choices=[("portrait", "Portrait")],
                        default="portrait",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("ready_for_provider", "Ready for provider"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=220)),
                ("provider", models.CharField(blank=True, default="", max_length=80)),
                ("prompt", models.TextField(blank=True, default="")),
                ("negative_prompt", models.TextField(blank=True, default="")),
                ("user_prompt_override", models.TextField(blank=True, default="")),
                ("prompt_packet_json", models.JSONField(blank=True, default=dict)),
                ("provider_request_json", models.JSONField(blank=True, default=dict)),
                ("provider_response_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_media_jobs",
                        to="story.committedscene",
                    ),
                ),
                (
                    "target_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_media_jobs",
                        to="story.character",
                    ),
                ),
                (
                    "visual_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_media_jobs",
                        to="story.charactervisualidentity",
                    ),
                ),
                (
                    "visual_identity_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_media_jobs",
                        to="story.charactervisualidentityversion",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_media_jobs",
                        to="story.world",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedMediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=story.models.generated_media_asset_upload_path
                    ),
                ),
                ("caption", models.TextField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=80)),
                (
                    "provider_asset_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_media_assets",
                        to="story.committedscene",
                    ),
                ),
                (
                    "target_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_media_assets",
                        to="story.character",
                    ),
                ),
                (
                    "visual_identity_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_media_assets",
                        to="story.charactervisualidentityversion",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_media_assets",
                        to="story.world",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="story.generatedmediajob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="generatedmediajob",
            index=models.Index(
                fields=["world", "status", "media_type"],
                name="story_gener_world_i_b174f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedmediajob",
            index=models.Index(
                fields=["world", "source", "created_at"],
                name="story_gener_world_i_84efcc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedmediajob",
            index=models.Index(
                fields=["source_scene", "created_at"],
                name="story_gener_source__94265c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedmediajob",
            index=models.Index(
                fields=["target_character", "created_at"],
                name="story_gener_target__51b9c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedmediaasset",
            index=models.Index(
                fields=["world", "created_at"], name="story_gener_world_i_19750c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedmediaasset",
            index=models.Index(
                fields=["source_scene", "created_at"],
                name="story_gener_source__390ac5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedmediaasset",
            index=models.Index(
                fields=["job", "created_at"], name="story_gener_job_id_08b940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedmediaasset",
            index=models.Index(
                fields=["target_character", "created_at"],
                name="story_gener_target__55ff25_idx",
            ),
        ),
    ]
