# Generated by Django 5.2.12 on 2026-07-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0036_generatedmediajob_generatedmediaasset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryArcUpdateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("horizon_reached", models.BooleanField(default=False)),
                ("evidence_summary", models.TextField(blank=True, default="")),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "current_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "current_phase",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "current_horizon",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("current_summary", models.TextField(blank=True, default="")),
                ("current_narrator_guidance", models.TextField(blank=True, default="")),
                ("current_constraints", models.TextField(blank=True, default="")),
                (
                    "proposed_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dormant", "Dormant"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "proposed_phase",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "proposed_horizon",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("proposed_summary", models.TextField(blank=True, default="")),
                (
                    "proposed_narrator_guidance",
                    models.TextField(blank=True, default=""),
                ),
                ("proposed_constraints", models.TextField(blank=True, default="")),
                ("raw_payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_arc_update_proposals",
                        to="story.committedscene",
                    ),
                ),
                (
                    "story_arc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_proposals",
                        to="story.storyarc",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_arc_update_proposals",
                        to="story.world",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["world", "status", "created_at"],
                        name="story_story_world_i_4206d8_idx",
                    ),
                    models.Index(
                        fields=["story_arc", "status", "created_at"],
                        name="story_story_story_a_6f7725_idx",
                    ),
                    models.Index(
                        fields=["source_scene", "status"],
                        name="story_story_source__235fbc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("story_arc", "source_scene"),
                        name="uniq_story_arc_update_proposal_per_scene",
                    )
                ],
            },
        ),
    ]
