# Generated by Django 5.2.12 on 2026-07-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0037_storyarcupdateproposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedmediajob",
            name="generation_mode",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait"),
                    ("video_image", "Image to video"),
                    ("video_text", "Text to video"),
                ],
                default="portrait",
                max_length=40,
            ),
        ),
    ]
