# Generated by Django 5.2.12 on 2026-07-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0038_alter_generatedmediajob_generation_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedmediajob",
            name="generation_mode",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait"),
                    ("scene_image", "Scene image"),
                    ("video_image", "Image to video"),
                    ("video_text", "Text to video"),
                ],
                default="portrait",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="GeneratedMediaJobSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("scene_role_summary", models.TextField(blank=True, default="")),
                (
                    "selected_reference_ids_json",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "primary_reference_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "identity_packet_snapshot_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_media_job_subjects",
                        to="story.character",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="story.generatedmediajob",
                    ),
                ),
                (
                    "visual_identity_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_media_job_subjects",
                        to="story.charactervisualidentityversion",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_media_job_subjects",
                        to="story.world",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "id"],
                "indexes": [
                    models.Index(
                        fields=["world", "character"],
                        name="story_gener_world_i_e4bb73_idx",
                    ),
                    models.Index(
                        fields=["job", "ordering"], name="story_gener_job_id_ec17c6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "character"),
                        name="uniq_media_job_subject_character",
                    )
                ],
            },
        ),
    ]
