# Generated by Django 5.2.12 on 2026-07-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0041_general_image_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyarc",
            name="current_phase",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="storyarc",
            name="horizon",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="storyarcupdateproposal",
            name="current_horizon",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="storyarcupdateproposal",
            name="current_phase",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="storyarcupdateproposal",
            name="proposed_horizon",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="storyarcupdateproposal",
            name="proposed_phase",
            field=models.TextField(blank=True, default=""),
        ),
    ]
